# Generated by Django 4.0.4 on 2022-05-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
