# Generated by Django 4.0.4 on 2022-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_patients',
            field=models.ManyToManyField(to='main.patient'),
        ),
    ]
